#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v21
# autospec commit: 8b93847
#
# Source0 file verified with key 0xBB463350D6EF31EF (heiko@shruuf.de)
#
Name     : kalgebra
Version  : 24.12.2
Release  : 39
URL      : https://download.kde.org/stable/release-service/24.12.2/src/kalgebra-24.12.2.tar.xz
Source0  : https://download.kde.org/stable/release-service/24.12.2/src/kalgebra-24.12.2.tar.xz
Source1  : https://download.kde.org/stable/release-service/24.12.2/src/kalgebra-24.12.2.tar.xz.sig
Source2  : BB463350D6EF31EF.pkey
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause CC0-1.0 GFDL-1.2 GPL-2.0 LGPL-2.0
Requires: kalgebra-bin = %{version}-%{release}
Requires: kalgebra-data = %{version}-%{release}
Requires: kalgebra-license = %{version}-%{release}
Requires: kalgebra-locales = %{version}-%{release}
BuildRequires : analitza-dev
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : extra-cmake-modules-data
BuildRequires : gnupg
BuildRequires : ncurses-dev
BuildRequires : qt6base-dev
BuildRequires : qt6webengine-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
No detailed description available

%package bin
Summary: bin components for the kalgebra package.
Group: Binaries
Requires: kalgebra-data = %{version}-%{release}
Requires: kalgebra-license = %{version}-%{release}

%description bin
bin components for the kalgebra package.


%package data
Summary: data components for the kalgebra package.
Group: Data

%description data
data components for the kalgebra package.


%package doc
Summary: doc components for the kalgebra package.
Group: Documentation

%description doc
doc components for the kalgebra package.


%package license
Summary: license components for the kalgebra package.
Group: Default

%description license
license components for the kalgebra package.


%package locales
Summary: locales components for the kalgebra package.
Group: Default

%description locales
locales components for the kalgebra package.


%prep
mkdir .gnupg
chmod 700 .gnupg
gpg --homedir .gnupg --import %{SOURCE2}
gpg --homedir .gnupg --status-fd 1 --verify %{SOURCE1} %{SOURCE0} > gpg.status
grep -E '^\[GNUPG:\] (GOODSIG|EXPKEYSIG) BB463350D6EF31EF' gpg.status
%setup -q -n kalgebra-24.12.2
cd %{_builddir}/kalgebra-24.12.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1738995027
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%cmake ..   -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1738995027
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/kalgebra
cp %{_builddir}/kalgebra-%{version}/COPYING %{buildroot}/usr/share/package-licenses/kalgebra/4cc77b90af91e615a64ae04893fdffa7939db84c || :
cp %{_builddir}/kalgebra-%{version}/COPYING.DOC %{buildroot}/usr/share/package-licenses/kalgebra/1bd373e4851a93027ba70064bd7dbdc6827147e1 || :
cp %{_builddir}/kalgebra-%{version}/COPYING.LIB %{buildroot}/usr/share/package-licenses/kalgebra/ba8966e2473a9969bdcab3dc82274c817cfd98a1 || :
cp %{_builddir}/kalgebra-%{version}/LICENSES/CC0-1.0.txt %{buildroot}/usr/share/package-licenses/kalgebra/82da472f6d00dc5f0a651f33ebb320aa9c7b08d0 || :
cp %{_builddir}/kalgebra-%{version}/LICENSES/GPL-2.0-or-later.txt %{buildroot}/usr/share/package-licenses/kalgebra/3cb34cfc72e87654683f2894299adf912d14b284 || :
cp %{_builddir}/kalgebra-%{version}/cmake/COPYING-CMAKE-SCRIPTS %{buildroot}/usr/share/package-licenses/kalgebra/ff3ed70db4739b3c6747c7f624fe2bad70802987 || :
export GOAMD64=v2
GOAMD64=v2
pushd clr-build
%make_install
popd
%find_lang kalgebra
%find_lang kalgebramobile

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/kalgebra
/usr/bin/kalgebramobile

%files data
%defattr(-,root,root,-)
/usr/share/applications/org.kde.kalgebra.desktop
/usr/share/applications/org.kde.kalgebramobile.desktop
/usr/share/icons/hicolor/64x64/apps/kalgebra.png
/usr/share/icons/hicolor/scalable/apps/kalgebra.svgz
/usr/share/katepart5/syntax/kalgebra.xml
/usr/share/metainfo/org.kde.graphsplasmoid.appdata.xml
/usr/share/metainfo/org.kde.kalgebra.appdata.xml
/usr/share/metainfo/org.kde.kalgebramobile.appdata.xml
/usr/share/plasma/plasmoids/org.kde.graphsplasmoid/contents/ui/config.ui
/usr/share/plasma/plasmoids/org.kde.graphsplasmoid/contents/ui/main.qml
/usr/share/plasma/plasmoids/org.kde.graphsplasmoid/metadata.json

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/HTML/ca/kalgebra/commands.docbook
/usr/share/doc/HTML/ca/kalgebra/index.cache.bz2
/usr/share/doc/HTML/ca/kalgebra/index.docbook
/usr/share/doc/HTML/ca/kalgebra/kalgebra-2dgraph-window.png
/usr/share/doc/HTML/ca/kalgebra/kalgebra-3dgraph-window.png
/usr/share/doc/HTML/ca/kalgebra/kalgebra-dictionary-window.png
/usr/share/doc/HTML/ca/kalgebra/kalgebra-main-window.png
/usr/share/doc/HTML/de/kalgebra/commands.docbook
/usr/share/doc/HTML/de/kalgebra/index.cache.bz2
/usr/share/doc/HTML/de/kalgebra/index.docbook
/usr/share/doc/HTML/de/kalgebra/kalgebra-main-window.png
/usr/share/doc/HTML/en/kalgebra/commands.docbook
/usr/share/doc/HTML/en/kalgebra/index.cache.bz2
/usr/share/doc/HTML/en/kalgebra/index.docbook
/usr/share/doc/HTML/en/kalgebra/kalgebra-2dgraph-window.png
/usr/share/doc/HTML/en/kalgebra/kalgebra-3dgraph-window.png
/usr/share/doc/HTML/en/kalgebra/kalgebra-console-window.png
/usr/share/doc/HTML/en/kalgebra/kalgebra-dictionary-window.png
/usr/share/doc/HTML/en/kalgebra/kalgebra-main-window.png
/usr/share/doc/HTML/en/kalgebra/view-fullscreen.png
/usr/share/doc/HTML/es/kalgebra/commands.docbook
/usr/share/doc/HTML/es/kalgebra/index.cache.bz2
/usr/share/doc/HTML/es/kalgebra/index.docbook
/usr/share/doc/HTML/es/kalgebra/kalgebra-main-window.png
/usr/share/doc/HTML/et/kalgebra/commands.docbook
/usr/share/doc/HTML/et/kalgebra/index.cache.bz2
/usr/share/doc/HTML/et/kalgebra/index.docbook
/usr/share/doc/HTML/it/kalgebra/commands.docbook
/usr/share/doc/HTML/it/kalgebra/index.cache.bz2
/usr/share/doc/HTML/it/kalgebra/index.docbook
/usr/share/doc/HTML/nl/kalgebra/commands.docbook
/usr/share/doc/HTML/nl/kalgebra/index.cache.bz2
/usr/share/doc/HTML/nl/kalgebra/index.docbook
/usr/share/doc/HTML/pt/kalgebra/commands.docbook
/usr/share/doc/HTML/pt/kalgebra/index.cache.bz2
/usr/share/doc/HTML/pt/kalgebra/index.docbook
/usr/share/doc/HTML/pt_BR/kalgebra/commands.docbook
/usr/share/doc/HTML/pt_BR/kalgebra/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kalgebra/index.docbook
/usr/share/doc/HTML/pt_BR/kalgebra/kalgebra-main-window.png
/usr/share/doc/HTML/ru/kalgebra/commands.docbook
/usr/share/doc/HTML/ru/kalgebra/index.cache.bz2
/usr/share/doc/HTML/ru/kalgebra/index.docbook
/usr/share/doc/HTML/ru/kalgebra/kalgebra-main-window.png
/usr/share/doc/HTML/sl/kalgebra/commands.docbook
/usr/share/doc/HTML/sl/kalgebra/index.cache.bz2
/usr/share/doc/HTML/sl/kalgebra/index.docbook
/usr/share/doc/HTML/sv/kalgebra/commands.docbook
/usr/share/doc/HTML/sv/kalgebra/index.cache.bz2
/usr/share/doc/HTML/sv/kalgebra/index.docbook
/usr/share/doc/HTML/uk/kalgebra/commands.docbook
/usr/share/doc/HTML/uk/kalgebra/index.cache.bz2
/usr/share/doc/HTML/uk/kalgebra/index.docbook
/usr/share/doc/HTML/uk/kalgebra/kalgebra-2dgraph-window.png
/usr/share/doc/HTML/uk/kalgebra/kalgebra-3dgraph-window.png
/usr/share/doc/HTML/uk/kalgebra/kalgebra-console-window.png
/usr/share/doc/HTML/uk/kalgebra/kalgebra-dictionary-window.png
/usr/share/doc/HTML/uk/kalgebra/kalgebra-main-window.png

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/kalgebra/1bd373e4851a93027ba70064bd7dbdc6827147e1
/usr/share/package-licenses/kalgebra/3cb34cfc72e87654683f2894299adf912d14b284
/usr/share/package-licenses/kalgebra/4cc77b90af91e615a64ae04893fdffa7939db84c
/usr/share/package-licenses/kalgebra/82da472f6d00dc5f0a651f33ebb320aa9c7b08d0
/usr/share/package-licenses/kalgebra/ba8966e2473a9969bdcab3dc82274c817cfd98a1
/usr/share/package-licenses/kalgebra/ff3ed70db4739b3c6747c7f624fe2bad70802987

%files locales -f kalgebra.lang -f kalgebramobile.lang
%defattr(-,root,root,-)

